import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import {Bitcount_Prop_Single} from "next/font/google";
import "./globals.css";
import {CameraProvider} from "./contexts/CameraContext";
import CameraToggle from "./components/CameraToggle";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const bitcountPropSingle = Bitcount_Prop_Single({
  variable: "--font-bitcount-prop-single",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${bitcountPropSingle.variable}`}
        suppressHydrationWarning
      >
        <CameraProvider>
          {children}
          <CameraToggle />
        </CameraProvider>
      </body>
    </html>
  );
}
